### ISSUE TITLE
Disappear the thumbnail in Example app

### ISSUE THREAD

**Issue by culumn** [marty-suzuki/SplittableViewKit#1]
### My Environment
- Xcode 10.0
- iOS Simulator
  - iPhone XS
  - iOS 12.0

### Description
Under the specific condition, disappear the thumbnail in example app.

The specific condition is:
1. Landscape
1. Content offset of the table view is not top.
1. `isFixedToTop` is on.

![2018-10-23 16 53 45](https://user-images.githubusercontent.com/22981133/47344906-84945000-d6e4-11e8-8474-9b29027bb2e0.gif)

**Comment by marty-suzuki** [comment]
@culumn 
Thank you for reporting.
I've fixed it (0b73a787d2de068b523afe82fa1693485cf453ce).

**Comment by culumn** [comment]
@marty-suzuki 
I checked that it works well.
Thanks for fixing :)
